# Generated by Django 4.0.5 on 2022-06-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
