# Generated by Django 4.0.5 on 2022-06-21 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('orders', '0002_alter_orderitems_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='seller',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='seller.seller'),
        ),
    ]
